vet_app/vet_app/config/routes.rb
VetApp::Application.routes.draw do
  resources :appointments

  resources :pets

  resources :customers

  resources :receptionists

  resources :doctors

  root :to => 'appointments#index'

end

vet_app/vet_app/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :pet
  attr_accessible :appointment_date, :reason, :reminder, :doctor_id, :pet_id

  validates :reason, :appointment_date, presence: true  
  validate  :future_appointment_date 

  def future_appointment_date
    if self.appointment_date and self.appointment_date.past?
      errors.add(:future_appointment_date, " must be in future")
    end
  end 
end
  

vet_app/vet_app/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointments }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
    @appointment = Appointment.new
    set_pets
    set_doctors

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @appointment = Appointment.find(params[:id])
    set_pets
    set_doctors
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(params[:appointment])

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render json: @appointment, status: :created, location: @appointment }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

private
  def set_doctors
    @doctors = Doctor.all
  end

  def set_pets
    @pets = Pet.all
  end
end

vet_app/vet_app/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

vet_app/vet_app/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appointment_date %><br />
    <%= f.datetime_select :appointment_date %>
  </div>
  <div class="field">
    <%= f.label :reminder %><br />
    <%= f.check_box :reminder %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_area :reason %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br />
    <%= f.text_field :doctor_id %>
  </div>
  <div class="field">
    <%= f.label :pet_id %><br />
    <%= f.text_field :pet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vet_app/vet_app/app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

vet_app/vet_app/app/views/appointments/index.html.erb
<div class="row-fluid">
<div class="span5 offset1">
<span class="label label-important"><h1>Listing appointments</h1></span>
<br />
<br />
<br />
<table class="table table-bordered table-condensed table-stripe table-hover">
  <tr>
    <th>Appointment date</th>
    <th>Reminder</th>
    <th>Reason</th>
    <th>Doctor</th>
    <th>Customer</th>
    <th>Pet</th>
    <th></th>
  </tr>

<% @appointments.each do |appointment| %>
  <tr>
    <td><i class="icon-calendar"></i><%= appointment.appointment_date %></td>
    <td><%= appointment.reminder %></td>
    <td><%= appointment.reason %></td>
    <td><%= appointment.doctor.name %></td>
    <td><%= appointment.pet.customer.name %></td>
    <td><%= appointment.pet.name %></td>
    <td><%= link_to '', edit_appointment_path(appointment), class: 'icon-pencil' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Appointment', new_appointment_path %>
</div>
</div>

vet_app/vet_app/app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

vet_app/vet_app/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Appointment date:</b>
  <%= @appointment.appointment_date %>
</p>

<p>
  <b>Reminder:</b>
  <%= @appointment.reminder %>
</p>

<p>
  <b>Reason:</b>
  <%= @appointment.reason %>
</p>

<p>
  <b>Doctor:</b>
  <%= @appointment.doctor %>
</p>

<p>
  <b>Pet:</b>
  <%= @appointment.pet %>
</p>


<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>